library(leaflet)
library(shinythemes)
library(shinyjs)
library(shinyBS)
library(data.table)
library(igraph)
library(ggplot2)
library(shiny)
library(ggvis)
library(timeDate)
library(tidyr)
library(dplyr)
library(sp)
library(maptools)
library(DT)
library(devtools)
library(ggthemr)
library(plotly)


load("my_work_space.RData")
